### ISSUE TITLE
Open file error with neotree

### ISSUE THREAD

**Issue by ravenxrz** [pteroctopus/faster.nvim#5]
<img width="1891" alt="image" src="https://github.com/user-attachments/assets/9af03b3c-5672-4393-9ef9-21f810a2a01c">

**Comment by ravenxrz** [comment]
I believe this plugin has conflicts with `okuuva/auto-save.nvim`

**Comment by pteroctopus** [comment]
Thank you. You are correct. The conflict is now solved. Please update the plugin and test.

I was able to reproduce the problem and after this fix it doesn't exist any more.
